#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local url_awless_Darwin="https://github.com/wallix/awless/releases/download/v${AWLESS_VERSION}/awless-darwin-amd64.tar.gz"
  local url_awless_Linux="https://github.com/wallix/awless/releases/download/v${AWLESS_VERSION}/awless-linux-amd64.tar.gz"

  local url_awless="url_awless_$(uname -s)"
  local fnm_awless="$(basename "${!url_awless}")-${AWLESS_VERSION}"
  cache curl "$fnm_awless" "${!url_awless}"

  mkdir -p "$shome/bin"
  pushd "$shome/bin"
  tar xfz  "${DATA}/cache/curl/$fnm_awless"
  chmod 755 "$shome/bin/awless"
  popd
}

main "$@"
