#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_awless="0.0.1"
  jq -n --arg awless "$ver_awless" '{awless: $awless}'
}

version "$@"
